config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'searches/searches'
  end
  # ーーーーーーーーーー管理者側ーーーーーーーーーーーー
  devise_for :admin, controllers: {
  sessions: 'admin/sessions'
      }


  namespace :admin do
    get 'admin/searches' => 'searches#searches'
    resources :customers,only: [:index, :show, :edit, :update]
    resources :order_details,only: [:index, :show, :update]
    resources :products,only: [:index, :show, :new, :edit, :update, :create]
    resources :genres,only: [:edit, :create, :index, :create, :update]
    resources :orders,only: [:update]
  end


 #  ーーーーーーーーーー顧客側ーーーーーーーーーーーー
  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations'
  }

  scope module: :public do
    root 'homes#top'
    get "homes/about" => "homes#about"
    get "/search" => "searches#searches"
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    get 'customers/withdraw' => 'customers#withdraw'
    resources :addresses,only: [:edit, :update, :show, :destroy, :index, :create]

    post 'orders/confirm' => 'orders#confirm'

    resources :customers,only: [:edit, :update, :show]
    resources :orders,only: [:new, :create]
    get 'order_details/thanks' => 'order_details#thanks'
    resources :order_details,only: [:edit, :update, :show, :destory, :index]
    resources :products,only: [:index, :show]
    resource :genres,only: [:index]
    resources :carts,only: [:new, :update, :destroy, :create]
      delete 'carts' => 'carts#destroy_all', as: 'cart_destroy'
  end




end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders
  has_many :cartitems



  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :phone_number, presence: true, length: { in: 10..11 }
  validates :address, presence: true


  def full_name
    first_name + last_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customer = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
     if @customer.update(customer_params)
     redirect_to admin_customers_path
    else
      render :edit
  end
  end

  private

  def customer_params
      params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana,
                                       :postal_code, :address, :phone_number, :email)
  end


end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">

<h4 class="title-3"> <%= @customer.first_name + @customer.last_name %>さんの会員情報  </h4>
</div>

  <%= form_with model:@customer,url:admin_customer_path,method: :PATCH,local:true do |f| %>
<div class="col">
<table class="table table-borderless">
  <tbody>
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      
      <tr>
        <th>氏名</th>
        <td><%= f.text_field :first_name %>　<%= f.text_field :last_name %></td>
      </tr>
      
      <tr>
      <th>フリガナ</th>
      <td><%= f.text_field :first_name_kana %>　<%= f.text_field :last_name_kana %></td>
      </tr>
      
      <tr>
      <th>郵便番号</th>
      <td><%= f.number_field :postal_code %></td>
      </tr>
      
      <tr>
      <th>住所</th>
      <td><%= f.text_field :address,size: 45 %></td>
      </tr>
      
      <tr>
      <th>電話番号</th>
      <td><%= f.telephone_field :phone_number %></td>
      </tr>
      
      <tr>
      <th>退会ステータス</th>
      <td><%= f.label :有効 %>
          <%= f.radio_button :is_deleted,:true %>
          <!--販売中【0】-->
          <%= f.label :退会 %>
          <%= f.radio_button :is_deleted,:false %></td>
          <!--販売停止【1】-->


      </tr>

      <tr>
      <th></th>
      <td><%= f.submit"変更を保存",class:"btn btn-secondary" %></td>
      </tr>

    </tbody>
  </table>
</div>
<% end %>
</div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
  <h4 class="title">会員一覧</h4>
 <table class="table table-hover m-2">
    <thead>
      <tr>
        <th scope="col">会員ID</th>
        <th scope="col">氏名</th>
        <th scope="col">メールアドレス</th>
        <th scope="col">ステータス</th>
      </tr>
    </thead>
    <% @customer.each do |costomer| %>
    <tbody>
      <tr>
        <th scope="row"><%= costomer.id %></th>
        <td><%= link_to costomer.first_name + costomer.last_name,admin_customer_path(costomer.id) %></td>
        <td><%= costomer.email %></td>

        <!--falseだったら、退会・入会判断-->
        <% if costomer.is_deleted == false %>
        　<td>退会済み</td>
        <% else %>
        <td>入会済み</td>
        <% end %>
        
      </tr>
    </tbody>
    <% end %>
 </table>
 </div>
   </div>
   <div class="col">
     <p class="text-center">
      <%= paginate @customer,class:'text-center'%>
      </p>
      </div>
     </div>


<!-- kaminariが使えない-->

app/views/admin/customers/show.html.erb
<div class="container">
   <h3 class="title-3"><%= @customer.first_name + @customer.last_name %>さんの会員詳細</h3>
  <div class="row m-3">
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>

        <tr>
          <th>氏名</th>
          <td><%= @customer.first_name + @customer.last_name %></td>
        </tr>

        <tr>
          <th>フリガナ</th>
          <td><%= @customer.first_name_kana + @customer.last_name_kana %></td>
        </tr>

        <tr>
          <th>郵便番号</th>
          <td><%= @customer.address %></td>
        </tr>

        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>


        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>


        <tr>
          <th>会員ステータス</th>
                <!--falseだったら、退会・入会判断-->
        <% if @customer.is_deleted == false %>
        　<td>有効</td>
        <% else %>
        <td>無効</td>
        <% end %>
        </tr>
        <tr>
        <th></th>
        <td><%= link_to "編集する",edit_admin_customer_path(@customer),class:'btn btn-danger m-3' %>
        <%= link_to "注文一覧を見る", admin_order_detail_path(@customer),class:'btn btn-primary' %></td>
        </tr>

      </tbody>
    </table> 
  </div>
</div>