config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'searches/searches'
  end
  # ーーーーーーーーーー管理者側ーーーーーーーーーーーー
  devise_for :admin, controllers: {
  sessions: 'admin/sessions'
      }


  namespace :admin do
    get 'admin/searches' => 'searches#searches'
    resources :customers,only: [:index, :show, :edit, :update]
    resources :order_details,only: [:index, :show, :update]
    resources :products,only: [:index, :show, :new, :edit, :update, :create]
    resources :genres,only: [:edit, :create, :index, :create, :update]
    resources :orders,only: [:update]
  end


 #  ーーーーーーーーーー顧客側ーーーーーーーーーーーー
  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations'
  }

  scope module: :public do
    root 'homes#top'
    get "homes/about" => "homes#about"
    get "/search" => "searches#searches"
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    get 'customers/withdraw' => 'customers#withdraw'
    resources :addresses,only: [:edit, :update, :show, :destroy, :index, :create]

    post 'orders/confirm' => 'orders#confirm'

    resources :customers,only: [:edit, :update, :show]
    resources :orders,only: [:new, :create]
    get 'order_details/thanks' => 'order_details#thanks'
    resources :order_details,only: [:edit, :update, :show, :destory, :index]
    resources :products,only: [:index, :show]
    resource :genres,only: [:index]
    resources :carts,only: [:new, :update, :destroy, :create]
      delete 'carts' => 'carts#destroy_all', as: 'cart_destroy'
  end




end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def full_address
    "#{postal_code} #{address} #{name}"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :customer
    belongs_to :product
    validates :quantity, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders
  has_many :cartitems



  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :phone_number, presence: true, length: { in: 10..11 }
  validates :address, presence: true


  def full_name
    first_name + last_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

has_many :order_details
belongs_to :customer, dependent: :destroy

enum order_status: {
  pay_waiting: 0,
  pay_up: 1,
  making: 2,
  ready_ship: 3,
  shipped: 4
}
# 入金待ち: 0,入金確認: 1,製作中: 2,発送準備中: 3, 発送済み: 4

enum payment_method: {
  クレジットカード: 0,
  銀行振込: 1
}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    enum making_status: {
        unintentional: 0,
        waiting_product: 1,
        in_preparation: 2,
        making_complete: 3,
    }
    # 制作不可: 0,制作待ち: 1,製作中: 2,製作完了": 3

end

app/models/product.rb
class Product < ApplicationRecord

    belongs_to :genre
    # ,optional: true
    has_many :order_details
    has_many :cartitems


    attachment :image
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    # before_action :authenticate_ad
    def index
        @genres = Genre.all
        @genre = Genre.new
    end
    def edit
        @genre = Genre.find(params[:id])
    end
    def create
        @genre = Genre.new(genre_params)
        if @genre.save
          redirect_to admin_genres_path
        else
            @genres = Genre.all
            render :index;
        end
    end
    def update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
        redirect_to admin_genres_path
    end
    
    private
    
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_details_path
  end

  private
  def order_params
  params.require(:order).permit(:order_status)
  end
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @product = Product.page(params[:page]).per(10)
  #   @product.genre_id = Genre.find(params[:product_id])
  end

  def show
   @product = Product.find(params[:id])
  end

  def new
    @new_product = Product.new
  end
  
  def create
    @new_product = Product.new(item_params)
    if @new_product.save
     redirect_to admin_products_path
    else 
    render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(item_params)
    redirect_to admin_products_path
  end

  private
  def item_params
    params.require(:product).permit(:introduction, :name, :genre_id, :price, :is_sale, :image)
  end


end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  def searches
  
        @value = params["search"]["value"]        #データを代入
        @how = params["search"]["how"]             #データを代入
        @datas = search_for(@how, @value)          #def search_forを実行(引数に検索ワードと検索方法)
      end
    
    
      private
    
      def match(value)
        #.orを使用することで、valueに一致するカラムのデータをnameカラムとgenre_idカラムから探してきます。
        Product.where(name: value).or(Product.where(genre_id: value))
      end
    
      def forward(value)                              #forward以降は商品名検索の定義しかしてません。
        Product.where("name LIKE ?", "#{value}%")
      end
    
      def backward(value)
        Product.where("name LIKE ?", "%#{value}")
      end
    
      def partical(value)
        Product.where("name LIKE ?", "%#{value}%")
      end
    
    
      def search_for(how, value)
        case how                     #引数のhowと一致する処理に進むように定義しています。
        when 'match'
        match(value)
        when 'forward'
          forward(value)
        when 'backward'
          backward(value)
        when 'partical'
          partical(value)

    end


  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
        products_path
    end

    def after_sign_up_path_for(resource)
        products_path
    end


    protected

    def  configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
    <div class="row">
         <h3 class="midashi">ジャンル編集</h3>
    </div>
   
    <%= form_with model: @genre, url: admin_genre_path, local: true do |f| %>
        <h4><%= f.label :name, "ジャンル名" %>🎉</h4>
        <%= f.text_field :name %>
    <%= f.submit "変更を保存",class: "btn btn-success" %>
    <% end %>
</div>
<style>
    h4{
        letter-spacing:5px;
        color:yellow;
        text-shadow: 2px 3px 4px silver;
    }
    body{
        background-color:#753;
    }
    .midashi {
        margin-top: 40px;
        margin-bottom: 50px;
        padding: 15px;
        background-color:  background: -webkit-gradient(linear, left top, left bottom, from(#422814), to(gray));
        background: linear-gradient(#422814, gray);;
        color: white;
        opacity:0.7;
        
    }
    .midashi:hover {
         background: -webkit-gradient(linear, left top, left bottom, from(purple), to(#bc8f8f));
        background: linear-gradient(purple, black);
      }
    
</style>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
      <h3 class=midashi>ジャンル一覧・追加画面<span class= "deco">🍰</span></h3>
    </div>
    <%= form_with model: @genre, url: admin_genres_path, method: :post, local:true do |f| %>
      <div class="row">
        <div class="col-md-3"><h5>ジャンル名を追加する<span class=migi>⇨</span></h5></div>
        <div class="new-text"><%= f.text_field :name, size:"30%" %></div>
        <div><%= f.submit '新規登録',class: "btn btn-danger" %></div>
      </div>
    <% end %>
    <h4>新規登録ボタンを押したらジャンルが保存されて下のテーブルに表示されます。</h4>
    <div class="row2">
      <div class="col-md-5">
          <table class="table">
           <tr>
             <th class="genre-thead">ジャンル名</th>
             <th class="genre-thead"></th>
             <th class="genre-thead"></th>
             <th class="genre-thead"></th>
             <th class="genre-thead"></th>
           </tr>
           <% @genres.each do |genre|%>
            <tr>
              <td class="genre-tbody"><%= genre.name %></td>
              <td class="genre-tbody"></td>
              <td class="genre-tbody"></td>
              <td class="genre-tbody"></td>
              <td class="genre-tbody"><%= link_to '編集する',edit_admin_genre_path(genre), class: "btn btn-primary" %></td>
            </tr>
           <% end %>
          </table>
      </div>
    </div>
    
</div>
 <style>
    body{
      background-color:#f0bc94;
    }
    .deco{
      margin-left:5px;
    }
    h4{
      color: red;
      margin-bottom: 50px;
    }
    h5 {
      letter-spacing:3px;
      color:indigo;
    }
    .migi {
      color:red;
    }
    .new-text{
      margin-bottom: 60px;
      margin-right: 20px;
    }
      .midashi {
        background: -webkit-gradient(linear, left top, left bottom, from(#422814), to(gray));
        background: linear-gradient(#422814, gray);
        color: silver;
        transition: .3s;
        margin-top: 30px;
        margin-bottom: 80px;
        padding: 15px;
      }
      .midashi:hover {
         background: -webkit-gradient(linear, left top, left bottom, from(purple), to(#bc8f8f));
        background: linear-gradient(purple, black);
      }
      .genre-thead {
        background: -webkit-gradient(linear, left top, left bottom, from(#422814), to(gray));
        background: linear-gradient(silver, gray);
        color: snow;
      }
      .genre-tbody{
        color: green;
        background-color:snow;
      }
    </style>

app/views/admin/orders/index.html.erb
<h1>Admin::Orders#index</h1>
<p>Find me in app/views/admin/orders/index.html.erb</p>

app/views/admin/products/_error.html.erb
<% if new_produc.errors.any? %>
  <%= new_produc.errors.count %>件のエラーが発生しました
  <% new_produc.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/admin/products/edit.html.erb
<div class="container">
     <div class="row justify-content-center">
      <div class="col-mt-5 ">
          <h4 class="title">商品編集</h4>

          <%= form_with model:@product,url:admin_product_path,method: :PATCH,local:true do |f| %>
              <table class="table table-borderless">
                <tbody>
                  <tr>
                    <th class="width40">商品画像</th>
                    <td><%=  f.attachment_field :image %></td>
                  </tr>

                  <tr>
                    <th>商品名</th>
                    <td><%= f.text_field :name%></td>
                  </tr>

                  <tr>
                    <th>商品説明</th>
                    <td><%= f.text_area :introduction%></td>
                  </tr>

                   <tr>
                    <th>ジャンル</th>
                    <td><%= f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] } ,include_blank: "--選択して下さい--" %></td>
                  </tr>
                   <tr>
                    <th>価格</th>
                    <td><%= f.number_field :price %></td>
                  </tr>
                  <tr>
                    <th>販売ステータス</th>
                      <td class:'form_edit'>
                      <%= f.label :販売中 %>
                      <%= f.radio_button :is_sale,:true %>
                      <%= f.label :販売停止 %>
                      <%= f.radio_button :is_sale,:false %>
                      </td>
                  </tr>
                 </tbody>
                </table>
                  <div class="text-center">
                    <%= f.submit "編集" ,class: "btn btn-primary text-center" %>
                 </div>
              </div>
          <% end %>
    </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row ">
     <h4 class="title">商品一覧</h4>
    <div class="mt ml-auto">
    <div class="text-right">
<%= link_to "+",new_admin_product_path,class:"btn btn-primary rounded-circle p-0",style:"width:2rem;height:2rem;" %>

 </div>
</div>
  <table class="table table-hover m-5">
    <thead>
      <tr>
        <th scope="col">商品ID</th>
        <th scope="col">商品名</th>
        <th scope="col">税抜き価格</th>
        <th scope="col">ジャンル</th>
        <th scope="col">ステータス</th>
      </tr>
    </thead>
    <% @product.each do |product|%>
    <tbody>
      <tr>
        <th class='width:40'><%= product.id %></th>
        <td><%= link_to product.name,admin_product_path(product) %></td>
        <td><%= number_to_currency(product.price,unit: "", format: "%n %u",strip_insignificant_zeros:true)%></td>

        <td><%= product.genre.name %></td>
        <%#=ジャンルが表示できない %>
        <% if product.is_sale == true %>
        <td>販売中</td>
         <% else %>
        <td>販売停止</td>
        <% end %>

      </tr>
    </tbody>
    <% end %>

  </table>
  </div>
</div>

<%= paginate @product %>

app/views/admin/products/new.html.erb
<div class="container">
     <div class="row justify-content-center"> 
      <div class="col-mt-5 ">
          <h4 class="title">商品登録</h4>

<% if @new_product.errors.any? %>
  <%= @new_product.errors.count %>件のエラーが発生しました
  <% @new_product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<%# i18nでエラー文が表示できない %>


          

          <%= form_with model: @new_product,url:admin_products_path,method: :post,local:true do |f| %>
              <table class="table table-borderless">
                <tbody>
                  <tr>
                    <th width="200">商品画像</th>
                    <td><%=  f.attachment_field :image %></td>
                  </tr>

                  <tr>
                    <th>商品名</th>
                    <td><%= f.text_field :name %></td>
                  </tr>

                  <tr>
                    <th>商品説明</th>
                    <td><%= f.text_area :introduction %></td>
                  </tr>

                   <tr>
                    <th>ジャンル</th>
                    <td><%= f.select :genre_id, Genre.all.map { |genre| [genre.name, genre.id] },:class => "mt-5" ,include_blank: "--選択して下さい--",select_id:"disabledSelect",class:"form-select" %></td>
                  </tr>

                   <tr>
                    <th>価格</th>
                    <td><%= f.number_field :price %></td>
                  </tr>
                   <tr>
                    <th>販売ステータス</th>
                    <td><%= f.label :販売 %>
                        <%= f.radio_button :is_sale,:true %>
                        <!--販売中【0】-->
                        <%= f.label :販売停止 %>
                        <%= f.radio_button :is_sale,:false %></td>
                        <!--販売停止【1】-->
                  </tr>

                 </tbody>
                </table>
                  <div class="text-center">
                    <%= f.submit "新規登録" ,class: "btn btn-primary text-center" %>
                 </div>
              </div>
          <% end %>
    </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row justify-content-center ">
    
    
    <div class="col">
        <h4 class="title-3">商品詳細</h4>
     <%= attachment_image_tag @product, :image,size:'450x300', fallback:"no_image.png" %>
    </div>
    
    
      <div class="col mt-5">
        <table class="table new-form-table text-align">
          <tbody >
            <tr>
              <th>商品名</th>
              <td><%= @product.name %></td>
              <td></td>
               <td></td>
            </tr>
              <tr>
              <th>商品説明</th>
              <td><%= @product.introduction%></td>
            </tr>
              <tr>
              <th>ジャンル</th>
              <td><%= @product.genre_id %></td>
            </tr>
              <tr>
              <th>税込価格<br/>(税抜価格)</th>
              <td><%= @product.price %></td>
            </tr>
              <tr>
              <th>販売ステータス</th>
              
             <% if @product.is_sale == true %>
              <td>販売中</td>
               <% else %>
              <td>販売停止</td>
             <% end %>
                          
              
            </tr>
          </tbody>
        </table>
            <%= link_to "編集する",edit_admin_product_path,class:'btn btn-primary btn-lg m-5'%>
      </div>
  
  
  
  </div>
</div>

app/views/admin/searches/searches.html.erb
<div class="container">
  <div class="row">
    <div class="col">
        <% if @datas.empty? %>
            <h2>該当する商品はありません</h2>
        <% end %>
        <% @datas.each do |product| %>
            <%= link_to product_path(product.id) do %>
                <div class="image"><%= attachment_image_tag product, :image, size: "200x200", fallback:"no_image.png" %></div>
                <div class="name"><%= product.name %></div>
                <div class="price">¥<%= number_to_currency(product.price,:precision =>0, :format=>"%n%u", :unit=>"円") %>（税抜き）</div>
            <% end %>
        <% end %>
    </div>
  </div>
</div>