config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'searches/searches'
  end
  # ーーーーーーーーーー管理者側ーーーーーーーーーーーー
  devise_for :admin, controllers: {
  sessions: 'admin/sessions'
      }


  namespace :admin do
    get 'admin/searches' => 'searches#searches'
    resources :customers,only: [:index, :show, :edit, :update]
    resources :order_details,only: [:index, :show, :update]
    resources :products,only: [:index, :show, :new, :edit, :update, :create]
    resources :genres,only: [:edit, :create, :index, :create, :update]
    resources :orders,only: [:update]
  end


 #  ーーーーーーーーーー顧客側ーーーーーーーーーーーー
  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations'
  }

  scope module: :public do
    root 'homes#top'
    get "homes/about" => "homes#about"
    get "/search" => "searches#searches"
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    get 'customers/withdraw' => 'customers#withdraw'
    resources :addresses,only: [:edit, :update, :show, :destroy, :index, :create]

    post 'orders/confirm' => 'orders#confirm'

    resources :customers,only: [:edit, :update, :show]
    resources :orders,only: [:new, :create]
    get 'order_details/thanks' => 'order_details#thanks'
    resources :order_details,only: [:edit, :update, :show, :destory, :index]
    resources :products,only: [:index, :show]
    resource :genres,only: [:index]
    resources :carts,only: [:new, :update, :destroy, :create]
      delete 'carts' => 'carts#destroy_all', as: 'cart_destroy'
  end




end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def full_address
    "#{postal_code} #{address} #{name}"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :customer
    belongs_to :product
    validates :quantity, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders
  has_many :cartitems



  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :phone_number, presence: true, length: { in: 10..11 }
  validates :address, presence: true


  def full_name
    first_name + last_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

has_many :order_details
belongs_to :customer, dependent: :destroy

enum order_status: {
  pay_waiting: 0,
  pay_up: 1,
  making: 2,
  ready_ship: 3,
  shipped: 4
}
# 入金待ち: 0,入金確認: 1,製作中: 2,発送準備中: 3, 発送済み: 4

enum payment_method: {
  クレジットカード: 0,
  銀行振込: 1
}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    enum making_status: {
        unintentional: 0,
        waiting_product: 1,
        in_preparation: 2,
        making_complete: 3,
    }
    # 制作不可: 0,制作待ち: 1,製作中: 2,製作完了": 3

end

app/models/product.rb
class Product < ApplicationRecord

    belongs_to :genre
    # ,optional: true
    has_many :order_details
    has_many :cartitems


    attachment :image
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    # before_action :authenticate_ad
    def index
        @genres = Genre.all
        @genre = Genre.new
    end
    def edit
        @genre = Genre.find(params[:id])
    end
    def create
        @genre = Genre.new(genre_params)
        if @genre.save
          redirect_to admin_genres_path
        else
            @genres = Genre.all
            render :index;
        end
    end
    def update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
        redirect_to admin_genres_path
    end
    
    private
    
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/admin/order_details_controller.rb
class Admin::OrderDetailsController < ApplicationController
    # before_action :authenticate_ad
    def index
        @orders = Order.page(params[:page]).per(20)
        # @order = Cartitem.find(params[:id])
        # @product = Product.all
    end
    
    def show
        @order = Order.find(params[:id])
		@order_detail = @order.order_details
    end
    
    def update
        @order = Order.find(params[:id])
        @order_detail = @order.order_details
        @order_detail.update(order_update_params)
        redirect_to admin_order_details_path
    end

    private
     def order_update_params
         params.require(:order_detail).permit(:making_status)
     end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_details_path
  end

  private
  def order_params
  params.require(:order).permit(:order_status)
  end
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  def index
    @product = Product.page(params[:page]).per(10)
  #   @product.genre_id = Genre.find(params[:product_id])
  end

  def show
   @product = Product.find(params[:id])
  end

  def new
    @new_product = Product.new
  end
  
  def create
    @new_product = Product.new(item_params)
    if @new_product.save
     redirect_to admin_products_path
    else 
    render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(item_params)
    redirect_to admin_products_path
  end

  private
  def item_params
    params.require(:product).permit(:introduction, :name, :genre_id, :price, :is_sale, :image)
  end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
        products_path
    end

    def after_sign_up_path_for(resource)
        products_path
    end


    protected

    def  configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/order_details/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
       <h1 class="itiran">注文画面一覧</h1>
       <h4>＼<span class="blank">下に表示されていますのでご確認ください⬇</span>／</h4>
       <div class=hitomitotakashi>👫</div>
       <table class="table table-bordered">
        <thead>
            <tr>
            　<th class="detail-thead">購入日時</th>
            　<th class="detail-thead">購入者</th>
            　<th class="detail-thead">注文個数</th>
            　<th class="detail-thead">ステータス</th>
            </tr>
          </thead>
          <tbody>
              <% @orders.each do |order| %>
              <tr>
                  <td class="detail-tbody"><%=link_to order.updated_at.strftime("%Y/%m/%d %H:%M"),admin_order_detail_path(order.id) %></td>
                　<td class="detail-tbody"><%= order.name %></td>
                　<% total=0 %>
                　<% order.order_details.each do |order_detail| %>
                　 <% total += order_detail.quantity %>
                　 <% end %>
                　<td class="detail-tbody"><%= total %></td>
                　<td class="detail-tbody"><%= order.order_status_i18n %></td>
            　</tr>
            　<% end %>
          </tbody>
        </table>
    </div>   
  </div>
</div>
<%= paginate @orders %>
<style>
    body{
        background-color:#422814;
    }
    .itiran{
        background: -webkit-gradient(linear, left top, left bottom, from(green), to(orange));
        background: linear-gradient(green, orange);
        color:snow;
        margin-top:35px;
        margin-bottom:30px;
    }
    .hitomitotakashi{
        font-size:30px;
        text-align:right;
    }
    h4{
        color: orange;
    }
    .blank{
        -webkit-animation: blink 1s ease-in-out infinite alternate;
        animation: blink 1s ease-in-out infinite alternate;
        color:coral;
    }
    @-webkit-keyframes blink{
        0% {opacity: 0;}
        100% {opacity: 1;}
    }
    .detail-thead {
        text-align:center;
        background: -webkit-gradient(linear, left top, left bottom, from(silver), to(gray));
        background: linear-gradient(silver, gray);
        color: snow;
    }
    .detail-tbody {
        background-color: snow;
        color: green;
    }
</style>

app/views/admin/order_details/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h3>注文履歴詳細</h3>
        <table class="table table-borderless ">
　        <tr>
　          <th style="width: 20%">購入者</th>
　          <td><%= link_to @order.name,admin_customer_path(@order.id) %> </td>
　        </tr>
　         <tr>
　           <th>注文日</th>
　           <td><%= @order.created_at.strftime("%Y/%m/%d %H:%M") %></td>
　         </tr>
      　   <tr>
      　      <th>配送先</th>
      　      <td><%= @order.addresses_name%></td>
      　   </tr>
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_method %></td>
    　     </tr>
          <tr>
　            <th>注文ステータス</th>

<%# ーーーーーーー注文ステータスーーーーーーーーーーーーーーー %>
              <td>
                <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
                  <%= f.select :order_status,Order.order_statuses_i18n.invert %>
                  <%= f.submit '更新', class: "btn btn-success btn-sm" %>
                <% end %>
              </td>
<%# ーーーーどこでUpdate保存すんの？Orderコントローラーない？detailコントローラーの中でorderのメソッド創設してストロングパラメータ？ーーーーーーーーーーーーーーーーーーー %>
　        </tr>
　        </table>
      </div>
    </div>
  </div>
<%# -----------上記ページ上段----------------- %>
 <div class="row">
    <div class="col m-5">
      <table class="table table">
　      <thead class="thead-light">
　        <tr>
　            <th class="detail-thead",>商品名</th>
　            <th class="detail-thead">単価</th>
　            <th class="detail-thead">数量</th>
　            <th class="detail-thead">小計</th>
　            <th class="detail-thead">制作ステータス</th>
　        </tr>
　       </thead>
　        <% @order_detail.each do |order_detail| %>
        <tbody>
　        <tr>
　            <td><%= order_detail.product.name %></td>
　            <td><%= number_to_currency(order_detail.product.price, :precision =>0, :unit=>"円", format: "%n %u",strip_insignificant_zeros:true) %></td>
　            <td><%= order_detail.quantity %></td>
　            <td><%= number_to_currency(order_detail.purchase_price, :precision =>0, :unit=>"円", format: "%n %u",strip_insignificant_zeros:true) %></td>


              <td>
<%# ーーーーー制作ステータスーーーーーー %>
          <%= form_with model: order_detail, url: admin_order_detail_path(order_detail),method: :patch, local:true do |f|%>
          <%= f.select :making_status,OrderDetail.making_statuses_i18n.invert %>
          <%= f.submit '更新', class: "btn btn-success btn-sm" %>
　         <% end %>
<%# ーーーーーー！！データは保存されているが、セレクトフォームに適用されない！！ーーーーーーー %>
　             </td>
          </tr>
          </tbody>
      <% end %>
    </table>
    <div class='col'>
  </div>
 </div>
<%# ---------------上記ページ下段左側----------------------- %>

  <!--商品値段-->

　  <div class="col">
　    <table class="table table-borderless">
　      <!--商品合計-->
　      <% total= 0 %>
　      <% @order_detail.each do |order_detail| %>
　      <% number_to_currency(total = total + ((order_detail.purchase_price).round(0) * order_detail.quantity), :precision =>0, :unit=>"円", format: "%n %u",strip_insignificant_zeros:true)  %>
        <% end %>


  <div class="col">
　      <tr>
　        <th>商品合計</th>
　        <td><%= total %>円</td>
　      </tr>
　      <tr>
　        <th>送料</th>
　        <td>800円</td>
　      </tr>
　      <tr>
　        <th>請求金額</th>
　        <td><%= total + 800 %>円</td>
　      </tr>
　    </table>
  </div>
　  </div>
　</div>
</div>








<%# -------style_tag-------- %>


<style>
  .detail-thead {
        text-align:center;
        background: -webkit-gradient(linear, left top, left bottom, from(silver), to(gray));
        background: linear-gradient(silver, gray);
        color: snow;
    }
</style>