config/routes.rb
Rails.application.routes.draw do


  namespace :admin do
    get 'searches/searches'
  end
  # ーーーーーーーーーー管理者側ーーーーーーーーーーーー
  devise_for :admin, controllers: {
  sessions: 'admin/sessions'
      }


  namespace :admin do
    get 'admin/searches' => 'searches#searches'
    resources :customers,only: [:index, :show, :edit, :update]
    resources :order_details,only: [:index, :show, :update]
    resources :products,only: [:index, :show, :new, :edit, :update, :create]
    resources :genres,only: [:edit, :create, :index, :create, :update]
    resources :orders,only: [:update]
  end


 #  ーーーーーーーーーー顧客側ーーーーーーーーーーーー
  devise_for :customers, controllers: {
    sessions: 'public/customers/sessions',
    registrations: 'public/customers/registrations'
  }

  scope module: :public do
    root 'homes#top'
    get "homes/about" => "homes#about"
    get "/search" => "searches#searches"
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    get 'customers/withdraw' => 'customers#withdraw'
    resources :addresses,only: [:edit, :update, :show, :destroy, :index, :create]

    post 'orders/confirm' => 'orders#confirm'

    resources :customers,only: [:edit, :update, :show]
    resources :orders,only: [:new, :create]
    get 'order_details/thanks' => 'order_details#thanks'
    resources :order_details,only: [:edit, :update, :show, :destory, :index]
    resources :products,only: [:index, :show]
    resource :genres,only: [:index]
    resources :carts,only: [:new, :update, :destroy, :create]
      delete 'carts' => 'carts#destroy_all', as: 'cart_destroy'
  end




end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer, optional: true

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true

  def full_address
    "#{postal_code} #{address} #{name}"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
    belongs_to :customer
    belongs_to :product
    validates :quantity, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :orders
  has_many :cartitems



  validates :first_name, presence: true
  validates :last_name,  presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :phone_number, presence: true, length: { in: 10..11 }
  validates :address, presence: true


  def full_name
    first_name + last_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

has_many :order_details
belongs_to :customer, dependent: :destroy

enum order_status: {
  pay_waiting: 0,
  pay_up: 1,
  making: 2,
  ready_ship: 3,
  shipped: 4
}
# 入金待ち: 0,入金確認: 1,製作中: 2,発送準備中: 3, 発送済み: 4

enum payment_method: {
  クレジットカード: 0,
  銀行振込: 1
}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :order
    belongs_to :product
    
    enum making_status: {
        unintentional: 0,
        waiting_product: 1,
        in_preparation: 2,
        making_complete: 3,
    }
    # 制作不可: 0,制作待ち: 1,製作中: 2,製作完了": 3

end

app/models/product.rb
class Product < ApplicationRecord

    belongs_to :genre
    # ,optional: true
    has_many :order_details
    has_many :cartitems


    attachment :image
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    # before_action :authenticate_ad
    def index
        @genres = Genre.all
        @genre = Genre.new
    end
    def edit
        @genre = Genre.find(params[:id])
    end
    def create
        @genre = Genre.new(genre_params)
        if @genre.save
          redirect_to admin_genres_path
        else
            @genres = Genre.all
            render :index;
        end
    end
    def update
        @genre = Genre.find(params[:id])
        @genre.update(genre_params)
        redirect_to admin_genres_path
    end
    
    private
    
    def genre_params
      params.require(:genre).permit(:name)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_details_path
  end

  private
  def order_params
  params.require(:order).permit(:order_status)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    def after_sign_in_path_for(resource)
        products_path
    end

    def after_sign_up_path_for(resource)
        products_path
    end


    protected

    def  configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :phone_number])
    end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="right">© All rights reserved by TansuiKabutu</div>
      </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganokaki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header>
      <div class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container">
          <%= link_to root_path do %>
            <% image_tag 'logo_image.png', size: "60x60" %>
          <% end %>
          <button class="navbar-toggler" type="button" date-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
       <%#　ーーーー カスタマー側ヘッダー ーーーーー%>
          <% if customer_signed_in? %>
            <div class="navbar-collapse collapse show" id="navbarNavDropdown">
            <h6 class="ml-5 text-white">ようこそ、<%= current_customer.first_name %>さん！</h6>
              <ul class="navbar-nav ml-auto nav">
                <li　class="btn1" id="icon">
                  <i class="fas fa-address-card" style="color:white;"></i><%= link_to "マイページ", customer_path(current_customer.id), class: 'navbar-brand' %>
                </li>
                <li　class="btn1" id="icon">
                  <i class="fas fa-cheese" style="color:white;"></i><%= link_to "商品一覧", products_path, class: 'navbar-brand' %>
                </li>
                <li　class="btn1" id="icon">
                  <i class="fas fa-shopping-cart" style="color:white;"></i><%= link_to "カート", new_cart_path, class: 'navbar-brand' %>
                </li>
                <li　class="btn1" id="icon">
                  <i class="fas fa-sign-out-alt" style="color:white;"></i><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'navbar-brand' %>
              </ul>
               <%= form_with url:search_path, method: :get, local:true do |f| %>
                <%= f.text_field "search[value]", placeholder: "Search" %>
                <%= f.select "search[how]", options_for_select({完全一致: :"match", 部分一致: :"partical"}) %>
                <%= f.submit "検索" %>
              <% end %>
            </div>
            <%#　ーーーー 管理側ヘッダー ーーーーー%>
          <% elsif admin_signed_in? %>
           <div id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto nav">
                <li　class="btn1">
                  <%= link_to "商品一覧", admin_products_path, class: 'navbar-brand' %>
                </li>
                <li　class="btn1">
                  <%= link_to "会員一覧", admin_customers_path , class: 'navbar-brand' %>
                </li>
                <li　class="btn1">
                  <%= link_to "注文商品一覧", admin_order_details_path, class: 'navbar-brand' %>
                </li>
                <li　class="btn1">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: 'navbar-brand' %>
                </li>
                <li　class="btn1">
                  <%= link_to "ログアウト",destroy_admin_session_path,method: :delete,class: 'navbar-brand' %>
                </li>
              </ul>
              <%= form_with url:admin_searches_searches_path, method: :get, local:true do |f| %>
                <%= f.text_field "search[value]", placeholder: "Search" %>
                <%= f.select "search[how]", options_for_select({完全一致: :"match", 部分一致: :"partical"}) %>
                <%= f.submit "検索" %>
              <% end %>
            </div>
              <%#　ーーーー どちらでもないヘッダー ーーーーー%>
          <% else %>
            <div class="navbar-collapse collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto nav">
                <li　class="btn">
                  <%= link_to "About", homes_about_path, class: 'navbar-brand' %>
                </li>
                <li　class="btn" id="icon">
                  <i class="fas fa-cheese" style="color:white;" ></i><%= link_to "商品一覧", products_path, class: 'navbar-brand' %>
                </li>
                <li　class="btn" id="icon">
                  <i class="fas fa-user-edit" style="color:white;"></i><%= link_to "新規登録", new_customer_registration_path, class: 'navbar-brand' %>
                </li>
                <li　class="btn" id="icon" style="color:white;">
                  <i class="fas fa-sign-in-alt"></i><%= link_to "ログイン", new_customer_session_path, class: 'navbar-brand' %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>

     <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </body>
</html>


<style>
footer {
  background: #343a40;
  height: 70px;
  width: 100%;
}

.right{
  color:white;
  text-align: center;
  line-height: 70px;
}

.icon {
 color:white;
}
</style>